name: cookflow
description: "CookFlow app"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  firebase_core: ^3.10.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.0

  # UI / helpers
  provider: ^6.1.2
  image_picker: ^1.1.0
  video_player: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
